application: uweb-isp
version: v2013-09-26
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /tasks/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app
  login: required

libraries:
- name: jinja2
  version: latest
