application: uweb-isp
version: v2014-04-08
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /tasks/.*
  script: main.app
  login: admin
  secure: always

- url: /.*
  script: main.app
  login: required
  secure: always

libraries:
- name: jinja2
  version: latest
